name: app_imobiliaria
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - lib/imagens/comprar.png
    - lib/imagens/alugar.png
    - lib/imagens/anucieaqui.png
    - lib/imagens/logo.png
    - lib/imagens/nossotime.png
    - lib/imagens/novos.png
    - lib/imagens/sobrenos.png
    - lib/imagens/semitem.JPG
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
